//_config.yml
title: Mohit Kumar
description: Frontend Developer | React, React Native, TypeScript, Firebase
theme: jekyll-theme-cayman # You can change this to another theme
show_downloads: false
google_analytics:
